#!/usr/bin/env bash
# On-device test harness for linux-cachyos-surface on a Surface Pro 9 (Intel).
#
# Run it from a clone of this repository on the Surface. Results go to
# build-reports/<date>-<uname -r>/ (SUMMARY.md, TESTED.md and raw outputs),
# ready to be committed to a report branch. MAC/IP addresses and UUIDs are
# masked, the hostname is left out, and camera frames are kept outside the
# repository (~/sp9-test-frames/) so nothing personal ends up in git.
#
# Usage: testing/sp9-test.sh <command> [options]
#
#   collect                   Snapshot of the running kernel and hardware, with
#                             automatic checks (about a minute)
#   cameras                   Capture test for each camera; saves one frame per
#                             camera under ~/sp9-test-frames/ for an orientation check
#   suspend [N] [SECS]        N s2idle cycles (default 10) woken by the RTC after
#                             SECS seconds (default 60), checking devices after each
#   drain                     Overnight battery drain: suspends until you wake it
#                             with the power button, then reports %/hour
#   load [SECS]               CPU load per platform profile (default 60 s each),
#                             sampling temperature, fan, clock and package power
#   checklist [--redo]        Guided manual checks, written to TESTED.md
#                             (resumable; --redo asks every question again)
#   all                       collect, cameras, checklist, then suspend 10 60
#
# suspend and drain also accept --no-suspend, which runs the checks without
# actually suspending (for testing the script itself).
#
# Environment: SP9_OUT overrides the report directory, SP9_FRAMES the frame
# directory.

set -u

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel 2>/dev/null || dirname "$SCRIPT_DIR")
KREL=$(uname -r)
DATE=$(date +%F)
OUT=${SP9_OUT:-$REPO_ROOT/build-reports/$DATE-$KREL}
FRAMES=${SP9_FRAMES:-$HOME/sp9-test-frames/$DATE-$KREL}

# Kernel messages that are known to be harmless on this machine (see the
# "Tested hardware" section of the README). Anything else is reported as new.
BENIGN_RE='ithc .*hid_input_report failed with -16|intel_ipu6\.psys.*Failed to get runtime PM|surface_serial_hub .*unhandled event|uses wireless extensions which will stop working|split lock detection|printk: Suspending console|TSC found unstable|Hibernation not supported|EFI stub: '

SEC_FILE=
SUDO_KEEPALIVE_PID=

# ---------------------------------------------------------------------------
# helpers

have() { command -v "$1" >/dev/null 2>&1; }

if [ -t 1 ]; then
    C_PASS=$'\e[32m' C_WARN=$'\e[33m' C_FAIL=$'\e[31m' C_DIM=$'\e[2m' C_OFF=$'\e[0m'
else
    C_PASS='' C_WARN='' C_FAIL='' C_DIM='' C_OFF=''
fi

info() { printf '%s\n' "$*"; }

# Mask things that identify the machine or network, everywhere.
mask() {
    local home_re='^$'
    [ "${#HOME}" -gt 1 ] && home_re=$HOME
    sed -E \
        -e 's/([0-9a-fA-F]{2}:){5}[0-9a-fA-F]{2}/xx:xx:xx:xx:xx:xx/g' \
        -e 's/[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}/<uuid>/g' \
        -e "s|$home_re|~|g"
}

# Network outputs additionally get IP addresses masked.
mask_net() {
    mask | sed -E \
        -e 's/\b([0-9]{1,3}\.){3}[0-9]{1,3}\b/x.x.x.x/g' \
        -e 's/\b[0-9a-fA-F]{1,4}(:[0-9a-fA-F]{0,4}){2,7}(\/[0-9]+)?\b/<ipv6>/g'
}

# Start a summary section; rows are appended to it with result().
section() {
    SEC_FILE="$OUT/.summary-$1.md"
    {
        printf '## %s\n\n' "$2"
        printf '| Check | Result | Detail |\n|---|---|---|\n'
    } > "$SEC_FILE"
    info ""
    info "== $2"
}

# result STATUS CHECK DETAIL   (STATUS: PASS WARN FAIL SKIP INFO)
result() {
    local status=$1 check=$2 detail=${3:-} color=
    case "$status" in
        PASS) color=$C_PASS ;;
        WARN) color=$C_WARN ;;
        FAIL) color=$C_FAIL ;;
        *) color=$C_DIM ;;
    esac
    printf '  %s%-4s%s %s%s\n' "$color" "$status" "$C_OFF" "$check" "${detail:+ - $detail}"
    detail=$(printf '%s' "$detail" | mask | tr '\n' ' ' | sed 's/|/\\|/g')
    printf '| %s | %s | %s |\n' "$check" "$status" "$detail" >> "$SEC_FILE"
}

# Rebuild SUMMARY.md from the per-command sections, in a fixed order.
write_summary() {
    local s
    {
        printf '# Surface Pro 9 test report: %s\n\n' "$KREL"
        # shellcheck disable=SC2016  # literal backticks for Markdown
        printf 'Generated by `testing/sp9-test.sh` on %s. Kernel: `%s`.\n\n' "$(date '+%F %H:%M')" "$(uname -srvmo)"
        for s in collect cameras suspend drain load checklist; do
            if [ -f "$OUT/.summary-$s.md" ]; then
                cat "$OUT/.summary-$s.md"
                printf '\n'
            fi
        done
    } > "$OUT/SUMMARY.md"
}

need_sudo() {
    [ "$(id -u)" -eq 0 ] && return 0
    [ -n "$SUDO_KEEPALIVE_PID" ] && return 0
    info "Some checks need root; sudo may ask for your password."
    sudo -v || { info "sudo failed; root-only checks will be skipped."; return 1; }
    ( while kill -0 "$$" 2>/dev/null; do sudo -n true 2>/dev/null; sleep 50; done ) &
    SUDO_KEEPALIVE_PID=$!
}

asroot() {
    if [ "$(id -u)" -eq 0 ]; then "$@"; else sudo -n "$@"; fi
}

cleanup() {
    [ -n "$SUDO_KEEPALIVE_PID" ] && kill "$SUDO_KEEPALIVE_PID" 2>/dev/null
    # shellcheck disable=SC2086
    [ -n "${LOAD_PIDS:-}" ] && kill $LOAD_PIDS 2>/dev/null
    [ -n "${RESTORE_PROFILE:-}" ] && printf '%s' "$RESTORE_PROFILE" | asroot tee /sys/firmware/acpi/platform_profile >/dev/null 2>&1
}
trap cleanup EXIT
trap 'exit 130' INT TERM

readf() { cat "$1" 2>/dev/null; }

# Kernel log for this boot, without hostname, firewall noise or identifiers.
kernel_log() {
    asroot journalctl -k -b --no-pager -o short-monotonic --no-hostname 2>/dev/null \
        | grep -v 'UFW BLOCK' | mask
}

# Warning-or-worse kernel messages since a given epoch, split into benign/new.
# Prints "[benign] ..." / "[NEW] ..." lines.
classify_warnings() {
    local since=$1
    asroot journalctl -k --no-pager -o short-monotonic --no-hostname -p warning --since="@$since" 2>/dev/null \
        | grep -v -e 'UFW BLOCK' -e '^-- ' | mask \
        | while IFS= read -r line; do
            if printf '%s' "$line" | grep -qE "$BENIGN_RE"; then
                printf '[benign] %s\n' "$line"
            else
                printf '[NEW] %s\n' "$line"
            fi
        done
}

boot_epoch() {
    local up
    up=$(cut -d. -f1 /proc/uptime)
    echo $(( $(date +%s) - up ))
}

pci_driver() {  # pci_driver VENDOR DEVICE -> driver name of the first match
    local d
    for d in /sys/bus/pci/devices/*; do
        if [ "$(readf "$d/vendor")" = "0x$1" ] && [ "$(readf "$d/device")" = "0x$2" ]; then
            if [ -e "$d/driver" ]; then basename "$(readlink "$d/driver")"; else echo "(none)"; fi
            return 0
        fi
    done
    return 1
}

hid_driver() {  # hid_driver VVVV:PPPP -> drivers of matching HID devices
    local d found=1
    for d in /sys/bus/hid/devices/*:"$1".*; do
        [ -e "$d" ] || continue
        found=0
        if [ -e "$d/driver" ]; then basename "$(readlink "$d/driver")"; else echo "(none)"; fi
    done
    return $found
}

input_names() { sed -n 's/^N: Name="\(.*\)"$/\1/p' /proc/bus/input/devices 2>/dev/null; }

input_event_node() {  # input_event_node "name substring" -> /dev/input/eventN
    awk -v pat="$1" '
        /^N: Name=/ { name = $0 }
        /^H: Handlers=/ {
            if (!index(name, pat)) next
            sub(/^H: Handlers=/, "")
            for (i = 1; i <= NF; i++) if ($i ~ /^event[0-9]+$/) { print "/dev/input/" $i; exit }
        }
    ' /proc/bus/input/devices 2>/dev/null
}

module_has() {  # module_has MODULE STRING -> 0 found, 1 not found, 2 no such module
    local path n
    path=$(modinfo -n "$1" 2>/dev/null) || return 2
    [ -e "$path" ] || return 2
    n=$(case "$path" in
            *.zst) zstd -dcq "$path" ;;
            *.xz) xz -dc "$path" ;;
            *.gz) gzip -dc "$path" ;;
            *) cat "$path" ;;
        esac 2>/dev/null | grep -aFc -- "$2")
    [ "${n:-0}" -gt 0 ]
}

subdev_for() {  # subdev_for SENSOR -> /dev/v4l-subdevN whose name starts with SENSOR
    local s
    for s in /sys/class/video4linux/v4l-subdev*; do
        [ -e "$s/name" ] || continue
        case "$(readf "$s/name")" in "$1"*) echo "/dev/$(basename "$s")"; return 0 ;; esac
    done
    return 1
}

bat_dir() { for b in /sys/class/power_supply/BAT*; do [ -d "$b" ] && { echo "$b"; return 0; }; done; return 1; }

ac_online() {
    local p
    for p in /sys/class/power_supply/*; do
        [ "$(readf "$p/type")" = "Mains" ] && [ "$(readf "$p/online")" = "1" ] && return 0
    done
    return 1
}

# Remaining battery energy in µWh (energy_now, or charge_now * voltage_now).
bat_energy() {
    local b
    b=$(bat_dir) || return 1
    if [ -r "$b/energy_now" ]; then readf "$b/energy_now"
    elif [ -r "$b/charge_now" ] && [ -r "$b/voltage_now" ]; then
        echo $(( $(readf "$b/charge_now") * $(readf "$b/voltage_now") / 1000000 ))
    else return 1; fi
}

bat_energy_full() {
    local b
    b=$(bat_dir) || return 1
    if [ -r "$b/energy_full" ]; then readf "$b/energy_full"
    elif [ -r "$b/charge_full" ] && [ -r "$b/voltage_min_design" ]; then
        echo $(( $(readf "$b/charge_full") * $(readf "$b/voltage_min_design") / 1000000 ))
    else return 1; fi
}

wifi_up() {
    local n
    for n in /sys/class/net/*; do
        [ -d "$n/wireless" ] && [ "$(readf "$n/operstate")" = "up" ] && return 0
    done
    return 1
}

bt_powered() { have bluetoothctl && bluetoothctl show 2>/dev/null | grep -q 'Powered: yes'; }

camera_count() {
    if have cam; then cam -l 2>/dev/null | grep -cE '^ *[0-9]+: '; else echo 0; fi
}

iptsd_active() { systemctl list-units 'iptsd@*' --state=active --no-legend --plain 2>/dev/null | grep -q .; }

# One-line device state used before and after suspend.
device_state() {
    local touch=0 iptsd=0 virt cover=0 wifi=0 bt=0 cams
    ls -d /sys/bus/hid/devices/*:045E:0C52.* >/dev/null 2>&1 && touch=1
    iptsd_active && iptsd=1
    virt=$(input_names | grep -c 'IPTSD Virtual')
    input_names | grep -q '045E:09AE' && cover=1
    wifi_up && wifi=1
    bt_powered && bt=1
    cams=$(camera_count)
    echo "touch=$touch iptsd=$iptsd iptsd_inputs=$virt cover=$cover wifi=$wifi bt=$bt cameras=$cams"
}

state_get() { printf '%s\n' "$1" | tr ' ' '\n' | sed -n "s/^$2=//p"; }

report_hint() {
    local rel=${OUT#"$REPO_ROOT"/}
    info ""
    info "Report: $OUT"
    info "When you're done testing, push it for review with:"
    info "  cd $REPO_ROOT"
    info "  git switch -c 7.2-sp9-test-report 2>/dev/null || git switch 7.2-sp9-test-report"
    info "  git add $rel && git commit -m \"Add Surface Pro 9 test report for $KREL\""
    info "  git push -u origin 7.2-sp9-test-report"
}

# ---------------------------------------------------------------------------
# collect

cmd_collect() {
    need_sudo
    local sys="$OUT/system" v drv f n missing
    mkdir -p "$sys"
    section collect "System snapshot ($(date '+%F %H:%M'))"

    # --- which kernel is this
    {
        uname -srvmo
        readf /proc/version
        echo
        have pacman && pacman -Qi linux-cachyos-surface 2>/dev/null | grep -E '^(Name|Version|Build Date|Install Date|Packager)'
        echo
        echo "cmdline: $(readf /proc/cmdline)"
    } | mask > "$sys/kernel.txt"
    v=$(pacman -Q linux-cachyos-surface 2>/dev/null | awk '{print $2}')
    if [ -n "$v" ] && [ "${KREL#"$v"}" != "$KREL" ]; then
        result PASS "Running linux-cachyos-surface" "$KREL (package $v)"
    else
        result WARN "Running linux-cachyos-surface" "running $KREL, installed package ${v:-none}"
    fi

    if [ -r /proc/config.gz ]; then
        zcat /proc/config.gz > "$sys/kernel.config"
        f="$REPO_ROOT/linux-cachyos-surface/config-$KREL"
        if [ -f "$f" ]; then
            if diff -q <(grep -E '^(CONFIG_|# CONFIG_)' "$f") <(grep -E '^(CONFIG_|# CONFIG_)' "$sys/kernel.config") >/dev/null; then
                result PASS "Kernel config matches this build" "linux-cachyos-surface/config-$KREL"
            else
                result WARN "Kernel config matches this build" "running config differs from linux-cachyos-surface/config-$KREL"
            fi
        else
            result SKIP "Kernel config matches this build" "no linux-cachyos-surface/config-$KREL in this clone"
        fi
    else
        result SKIP "Kernel config" "/proc/config.gz not available"
    fi

    module_has ov13858 "upside-down module, rotation=180"
    case $? in
        0) result PASS "local-0101 (rear camera rotation/flip) built in" "marker found in ov13858.ko" ;;
        1) result FAIL "local-0101 (rear camera rotation/flip) built in" "marker missing from ov13858.ko" ;;
        *) result SKIP "local-0101 (rear camera rotation/flip) built in" "ov13858 module not found" ;;
    esac
    module_has intel_skl_int3472_discrete "Failed to register type 0x%02x"
    case $? in
        0) result PASS "local-0100 (int3472 fix) built in" "marker found in intel_skl_int3472_discrete.ko" ;;
        1) result FAIL "local-0100 (int3472 fix) built in" "marker missing from intel_skl_int3472_discrete.ko" ;;
        *) result SKIP "local-0100 (int3472 fix) built in" "int3472 module not found" ;;
    esac

    # --- health
    v=$(readf /proc/sys/kernel/tainted)
    if [ "$v" = "0" ]; then result PASS "Kernel not tainted"
    else
        local bits="" i
        for i in $(seq 0 19); do (( (v >> i) & 1 )) && bits+="$i "; done
        result WARN "Kernel not tainted" "tainted=$v (bits ${bits% })"
    fi
    if ! systemctl --failed --no-legend --plain > "$sys/failed-units.txt" 2>&1; then
        result SKIP "No failed systemd units" "systemctl not usable"
    elif [ -s "$sys/failed-units.txt" ]; then
        result WARN "No failed systemd units" "$(awk '{print $1}' "$sys/failed-units.txt" | tr '\n' ' ')"
    else
        result PASS "No failed systemd units"
    fi

    kernel_log | grep -v '^-- ' > "$OUT/kernel.log"
    v=$(sed -n '1s/^\[ *\([0-9]*\)\..*/\1/p' "$OUT/kernel.log")
    if [ -s "$OUT/kernel.log" ] && [ "${v:-99}" -lt 5 ]; then
        result PASS "Full kernel log of this boot captured" "$(wc -l < "$OUT/kernel.log") lines"
    elif [ -s "$OUT/kernel.log" ]; then
        result WARN "Full kernel log of this boot captured" "log starts at ${v}s, early boot missing"
    else
        result FAIL "Full kernel log of this boot captured" "journalctl returned nothing"
    fi
    classify_warnings "$(boot_epoch)" > "$OUT/kernel-warnings.txt"
    n=$(grep -c '^\[NEW\]' "$OUT/kernel-warnings.txt")
    if [ ! -s "$OUT/kernel.log" ]; then
        result SKIP "No kernel oops/BUG/WARN splats" "no kernel log"
    elif grep -qE 'Call Trace|BUG:|Oops|WARNING: CPU|general protection fault' "$OUT/kernel.log"; then
        result FAIL "No kernel oops/BUG/WARN splats" "see kernel.log"
    else
        result PASS "No kernel oops/BUG/WARN splats"
    fi
    if [ ! -s "$OUT/kernel.log" ]; then
        result SKIP "No unexpected kernel warnings" "no kernel log"
    elif [ "$n" -eq 0 ]; then
        result PASS "No unexpected kernel warnings" "$(grep -c '^\[benign\]' "$OUT/kernel-warnings.txt") known-benign"
    else
        result WARN "No unexpected kernel warnings" "$n new warning lines, see kernel-warnings.txt"
    fi

    # --- PCI, HID and SAM drivers
    have lspci && lspci -nnk > "$sys/lspci.txt" 2>&1
    lsmod > "$sys/lsmod.txt" 2>&1
    local spec want label
    for spec in "51d0 ithc Touch/pen controller" "465d intel-ipu6 Camera ISP (IPU6)" "51f0 iwlwifi Wi-Fi" "466d thunderbolt Thunderbolt" "46a8 i915|xe Graphics"; do
        read -r n want label <<< "$spec"
        drv=$(pci_driver 8086 "$n") || { result SKIP "$label driver" "PCI 8086:$n not present"; continue; }
        if printf '%s' "$drv" | grep -qxE "$want"; then result PASS "$label driver" "8086:$n bound to $drv"
        else result FAIL "$label driver" "8086:$n bound to $drv, expected $want"; fi
    done
    drv=$(pci_driver 8086 51c8) && result INFO "Audio controller driver" "8086:51c8 bound to $drv (snd_hda_intel = legacy HDA, sof-audio-pci-intel-tgl = SOF)"

    for f in /sys/bus/hid/devices/*; do
        [ -e "$f" ] || continue
        printf '%s %s\n' "$(basename "$f")" "$( [ -e "$f/driver" ] && basename "$(readlink "$f/driver")" || echo '(none)')"
    done > "$sys/hid-devices.txt"
    drv=$(hid_driver 045E:0C52 | tr '\n' ' ')
    if [ -n "$drv" ]; then result PASS "Touch HID device (ithc 045E:0C52)" "driver $drv"
    else result FAIL "Touch HID device (ithc 045E:0C52)" "not present"; fi
    drv=$(hid_driver 045E:09AE | tr '\n' ' ')
    if [ -n "$drv" ]; then
        if printf '%s' "$drv" | grep -qw surface; then result PASS "Type Cover keyboard uses hid-surface" "045E:09AE -> $drv"
        else result WARN "Type Cover keyboard uses hid-surface" "045E:09AE -> $drv"; fi
    else
        result SKIP "Type Cover keyboard uses hid-surface" "keyboard not present (Type Cover detached?)"
    fi
    drv=$(hid_driver 045E:09AF | tr '\n' ' ')
    if [ -n "$drv" ]; then
        if printf '%s' "$drv" | grep -qw hid-multitouch; then result PASS "Type Cover touchpad uses hid-multitouch" "045E:09AF -> $drv"
        else result WARN "Type Cover touchpad uses hid-multitouch" "045E:09AF -> $drv"; fi
    else
        result SKIP "Type Cover touchpad uses hid-multitouch" "touchpad not present (Type Cover detached?)"
    fi

    for f in /sys/bus/surface_aggregator/devices/*; do
        [ -e "$f" ] || continue
        printf '%s %s\n' "$(basename "$f")" "$( [ -e "$f/driver" ] && basename "$(readlink "$f/driver")" || echo '(none)')"
    done > "$sys/sam-devices.txt"
    missing=""
    for n in surface_aggregator surface_aggregator_registry surface_aggregator_hub surface_hid surface_hid_core \
             surface_battery surface_charger surface_aggregator_tabletsw surface_platform_profile surface_fan \
             surface_temp surface_gpe ithc hid_surface; do
        grep -q "^$n " "$sys/lsmod.txt" || missing+="$n "
    done
    if [ -z "$missing" ]; then result PASS "Surface modules loaded" "SAM, HID, battery, charger, tablet switch, profile, fan, temp, GPE, ithc, hid-surface"
    else result WARN "Surface modules loaded" "missing: $missing"; fi

    # --- input devices and sensors
    input_names > "$sys/input-devices.txt"
    for spec in "IPTSD Virtual Touchscreen" "IPTSD Virtual Stylus" "Tablet Mode Switch"; do
        if grep -qF "$spec" "$sys/input-devices.txt"; then result PASS "Input device: $spec"
        else result FAIL "Input device: $spec" "not found"; fi
    done
    if iptsd_active; then result PASS "iptsd running" "$(systemctl list-units 'iptsd@*' --state=active --no-legend --plain | awk '{print $1}' | tr '\n' ' ')"
    else result FAIL "iptsd running" "no active iptsd@ unit"; fi

    for f in /sys/bus/iio/devices/iio:device*; do
        [ -e "$f/name" ] && printf '%s %s\n' "$(basename "$f")" "$(readf "$f/name")"
    done > "$sys/iio-devices.txt"
    n=$(awk '{print $2}' "$sys/iio-devices.txt" | sort -u | tr '\n' ' ')
    if grep -q accel_3d "$sys/iio-devices.txt" && grep -q als "$sys/iio-devices.txt"; then
        result PASS "Sensors (accelerometer, light sensor)" "$n"
    else
        result WARN "Sensors (accelerometer, light sensor)" "found: ${n:-none}"
    fi
    have monitor-sensor && timeout 4 monitor-sensor > "$sys/monitor-sensor.txt" 2>&1

    # --- cameras
    mkdir -p "$OUT/cameras"
    for f in /sys/class/video4linux/v4l-subdev*; do
        [ -e "$f/name" ] && printf '%s %s\n' "$(basename "$f")" "$(readf "$f/name")"
    done > "$OUT/cameras/subdevs.txt"
    local sensor sub
    for sensor in ov5693 ov13858; do
        if sub=$(subdev_for "$sensor"); then
            result PASS "Camera sensor $sensor probed" "$sub"
            have v4l2-ctl && v4l2-ctl -d "$sub" --list-ctrls > "$OUT/cameras/$sensor-ctrls.txt" 2>&1
        else
            result FAIL "Camera sensor $sensor probed" "no v4l subdev"
        fi
    done
    if [ -s "$OUT/cameras/ov13858-ctrls.txt" ]; then
        if grep -q horizontal_flip "$OUT/cameras/ov13858-ctrls.txt" && grep -q vertical_flip "$OUT/cameras/ov13858-ctrls.txt"; then
            result PASS "Rear sensor has flip controls (local-0101)"
        else
            result FAIL "Rear sensor has flip controls (local-0101)" "no horizontal_flip/vertical_flip"
        fi
        v=$(sed -n 's/.*camera_sensor_rotation.*value=\([0-9]*\).*/\1/p' "$OUT/cameras/ov13858-ctrls.txt")
        if [ "$v" = "180" ]; then result PASS "Rear sensor rotation is 180" ; else result FAIL "Rear sensor rotation is 180" "rotation=${v:-unknown}"; fi
    fi
    if subdev_for ov7251 >/dev/null; then result INFO "IR camera (ov7251)" "probed"
    else result INFO "IR camera (ov7251)" "not probed (same as 7.1)"; fi
    if have cam; then
        cam -l > "$OUT/cameras/cam-list.txt" 2>/dev/null
        n=$(grep -cE '^ *[0-9]+: ' "$OUT/cameras/cam-list.txt")
        if [ "$n" -ge 2 ]; then result PASS "libcamera lists front and rear cameras" "$n cameras"
        else result FAIL "libcamera lists front and rear cameras" "$n cameras"; fi
    else
        result SKIP "libcamera lists front and rear cameras" "cam (libcamera-tools) not installed"
    fi
    for n in OVTI5693 OVTID858 OVTI7251 INT3472 INT33BE INT347E; do
        for f in /sys/bus/acpi/devices/"$n":*; do
            [ -e "$f" ] || continue
            printf '%s status=%s physical_node=%s\n' "$(basename "$f")" "$(readf "$f/status")" \
                "$( [ -e "$f/physical_node" ] && basename "$(readlink "$f/physical_node")" || echo none)"
        done
    done > "$OUT/cameras/acpi-camera-devices.txt"
    grep -iE 'int3472|ov5693|ov13858|ov7251|ipu6|ipu-bridge|ipu_bridge' "$OUT/kernel.log" > "$OUT/cameras/kernel-camera.log"

    # --- power and thermals
    for f in /sys/class/power_supply/*; do
        [ -e "$f/uevent" ] || continue
        echo "== $(basename "$f")"
        grep -v -e SERIAL -e MODEL_NAME "$f/uevent"
    done > "$sys/power-supply.txt" 2>&1
    if f=$(bat_dir); then
        result PASS "Battery reporting" "$(readf "$f/capacity")% $(readf "$f/status")"
    else
        result FAIL "Battery reporting" "no BAT* power supply"
    fi
    if ac_online; then result INFO "AC adapter" "online"; else result INFO "AC adapter" "offline"; fi
    if [ -r /sys/firmware/acpi/platform_profile ]; then
        result PASS "Platform profile" "$(readf /sys/firmware/acpi/platform_profile) (choices: $(readf /sys/firmware/acpi/platform_profile_choices))"
    else
        result FAIL "Platform profile" "/sys/firmware/acpi/platform_profile missing"
    fi
    {
        for f in /sys/class/hwmon/hwmon*; do
            echo "== $(basename "$f") $(readf "$f/name")"
            for n in "$f"/temp*_input "$f"/fan*_input; do
                [ -e "$n" ] || continue
                printf '%s %s %s\n' "$(basename "$n")" "$(readf "${n%_input}_label")" "$(readf "$n")"
            done
        done
        echo
        for f in /sys/class/thermal/thermal_zone*; do
            printf '%s %s %s\n' "$(basename "$f")" "$(readf "$f/type")" "$(readf "$f/temp")"
        done
    } > "$sys/thermal.txt" 2>&1
    if grep -q '^fan[0-9]*_input' "$sys/thermal.txt"; then result PASS "Fan speed reported" "$(grep -m1 '^fan[0-9]*_input' "$sys/thermal.txt" | awk '{print $NF}') rpm"
    else result WARN "Fan speed reported" "no fan*_input in hwmon"; fi

    # --- audio
    {
        echo "== aplay -l"; aplay -l 2>&1
        echo "== arecord -l"; arecord -l 2>&1
        echo "== /proc/asound/cards"; readf /proc/asound/cards
        if have wpctl; then echo "== wpctl status"; wpctl status 2>&1; fi
    } > "$sys/audio.txt"
    if arecord -l 2>/dev/null | grep -q '^card'; then result PASS "Capture (microphone) device exists" "$(arecord -l 2>/dev/null | grep -c '^card') capture device(s)"
    else result WARN "Capture (microphone) device exists" "arecord -l lists none"; fi
    if aplay -l 2>/dev/null | grep -q '^card'; then result PASS "Playback device exists"
    else result FAIL "Playback device exists" "aplay -l lists none"; fi

    # --- network
    {
        have nmcli && nmcli -t -f DEVICE,TYPE,STATE device 2>&1
        have rfkill && rfkill list 2>&1
        have bluetoothctl && bluetoothctl show 2>&1 | grep -E 'Powered|Discoverable|Pairable'
        have boltctl && boltctl list 2>&1
    } | mask_net > "$sys/network.txt"
    if wifi_up; then result PASS "Wi-Fi interface up"; else result WARN "Wi-Fi interface up" "no wireless interface is up"; fi
    if bt_powered; then result PASS "Bluetooth powered"; else result INFO "Bluetooth powered" "no (or bluetoothctl missing)"; fi

    # --- suspend support
    {
        echo "mem_sleep: $(readf /sys/power/mem_sleep)"
        echo "state: $(readf /sys/power/state)"
        for f in /sys/power/suspend_stats/*; do [ -f "$f" ] && echo "suspend_stats/$(basename "$f"): $(readf "$f")"; done
    } > "$sys/suspend.txt"
    if grep -q '\[s2idle\]' "$sys/suspend.txt"; then result PASS "Suspend mode is s2idle"
    else result WARN "Suspend mode is s2idle" "$(readf /sys/power/mem_sleep)"; fi
    if [ -r /sys/power/suspend_stats/total_hw_sleep ] && grep -q '^intel_pmc_core ' "$sys/lsmod.txt"; then
        result PASS "Hardware sleep (S0ix) accounting available" "intel_pmc_core loaded"
    else
        result WARN "Hardware sleep (S0ix) accounting available" "intel_pmc_core not loaded or no suspend_stats/total_hw_sleep"
    fi

    # --- CachyOS features from the 7.2 config
    {
        echo "tcp_available_congestion_control: $(readf /proc/sys/net/ipv4/tcp_available_congestion_control)"
        echo "tcp_congestion_control: $(readf /proc/sys/net/ipv4/tcp_congestion_control)"
        echo "sched_ext: $(readf /sys/kernel/sched_ext/state)"
        echo "thp enabled: $(readf /sys/kernel/mm/transparent_hugepage/enabled)"
        echo "thp shmem_enabled: $(readf /sys/kernel/mm/transparent_hugepage/shmem_enabled)"
        have systemd-analyze && { echo; systemd-analyze 2>&1; }
    } > "$sys/cachyos.txt"
    if modinfo tcp_bbr3 >/dev/null 2>&1 || grep -qw bbr3 /proc/sys/net/ipv4/tcp_available_congestion_control 2>/dev/null; then
        result PASS "BBR3 available" "tcp_bbr3 (congestion control \"bbr3\")"
    else
        result WARN "BBR3 available" "tcp_bbr3 module not found"
    fi
    if [ -r /sys/kernel/sched_ext/state ]; then result PASS "sched_ext available" "state: $(readf /sys/kernel/sched_ext/state)"
    else result WARN "sched_ext available" "/sys/kernel/sched_ext missing"; fi
    result INFO "Boot time" "$(systemd-analyze 2>/dev/null | head -1 | sed 's/^Startup finished in //')"

    write_summary
}

# ---------------------------------------------------------------------------
# cameras

cmd_cameras() {
    need_sudo
    local dir="$OUT/cameras" idx name props loc rot log t0 frames fps errs last png
    mkdir -p "$dir" "$FRAMES"
    section cameras "Cameras ($(date '+%F %H:%M'))"
    if ! have cam; then
        result SKIP "Camera capture" "cam (libcamera-tools) not installed"
        write_summary; return
    fi
    cam -l 2>/dev/null | sed -n 's/^ *\([0-9][0-9]*\): \(.*\)$/\1|\2/p' > "$dir/.list"
    if [ ! -s "$dir/.list" ]; then
        result FAIL "Camera capture" "libcamera found no cameras"
        write_summary; return
    fi
    info "Point the cameras at something with recognizable up/down (not your face if you'd rather not)."
    info "Each camera captures 60 frames, then 12 more to save one frame."
    while IFS='|' read -r idx name; do
        props=$(cam -c "$idx" -p 2>/dev/null)
        printf '%s\n' "$props" > "$dir/cam$idx-properties.txt"
        loc=$(printf '%s\n' "$props" | sed -n 's/.*Location = \([0-9]*\).*/\1/p' | head -1)
        rot=$(printf '%s\n' "$props" | sed -n 's/.*Rotation = \([0-9]*\).*/\1/p' | head -1)
        case "$loc" in 0) loc=front ;; 1) loc=rear ;; 2) loc=external ;; *) loc="camera $idx" ;; esac
        name=$(printf '%s' "$name" | sed 's/\\/\\\\/g')
        result INFO "$loc camera properties" "$name, rotation ${rot:-?}"
        if [ "$loc" = rear ]; then
            if [ "$rot" = 180 ]; then result PASS "Rear camera reports rotation 180"
            else result FAIL "Rear camera reports rotation 180" "rotation=${rot:-?}"; fi
        fi

        log="$dir/cam$idx-capture.log"
        t0=$(date +%s)
        timeout 45 cam -c "$idx" -C 60 > "$log" 2>&1
        sleep 1
        frames=$(grep -c ' seq: ' "$log")
        fps=$(sed -n 's/.*(\([0-9.]*\) fps).*/\1/p' "$log" | tail -n 40 | awk '$1 > 0 { s += $1; n++ } END { if (n) printf "%.1f", s / n; else print 0 }')
        if [ "$frames" -ge 55 ]; then result PASS "$loc camera streams" "$frames/60 frames, ${fps} fps"
        else result FAIL "$loc camera streams" "$frames/60 frames in 45 s"; fi
        if grep -q 'Camera configuration adjusted' "$log"; then
            result WARN "$loc camera upright without adjustment" "libcamera adjusted the configuration (orientation not achievable?)"
        else
            result PASS "$loc camera upright without adjustment" "libcamera accepted orientation rot0"
        fi
        errs=$(classify_warnings "$t0" | grep '^\[NEW\]' | grep -iE 'time ?out|isys|csi|ov5693|ov13858|ipu|int3472|frame')
        printf '%s\n' "$errs" > "$dir/cam$idx-kernel.log"
        if printf '%s' "$errs" | grep -qiE 'stream stop time ?out|timed out|timeout'; then
            result FAIL "$loc camera: no capture errors in kernel log" "$(printf '%s' "$errs" | grep -iE 'time ?out' | head -1)"
        elif [ -n "$errs" ]; then
            result WARN "$loc camera: no capture errors in kernel log" "$(printf '%s\n' "$errs" | grep -c .) camera-related warning(s), see cameras/cam$idx-kernel.log"
        else
            result PASS "$loc camera: no capture errors in kernel log"
        fi

        rm -f "$FRAMES"/cam"$idx"-*.ppm
        timeout 30 cam -c "$idx" -C 12 --file="$FRAMES/cam$idx-#.ppm" > /dev/null 2>&1
        last=$(find "$FRAMES" -maxdepth 1 -name "cam$idx-*.ppm" -printf '%T@ %p\n' 2>/dev/null | sort -n | tail -1 | cut -d' ' -f2-)
        if [ -n "$last" ]; then
            png="$FRAMES/$loc-camera.png"
            if have magick; then magick "$last" -resize 50% "$png" && rm -f "$FRAMES"/cam"$idx"-*.ppm
            elif have convert; then convert "$last" -resize 50% "$png" && rm -f "$FRAMES"/cam"$idx"-*.ppm
            elif have ffmpeg; then ffmpeg -loglevel error -y -i "$last" -vf scale=iw/2:-1 "$png" && rm -f "$FRAMES"/cam"$idx"-*.ppm
            else png="$FRAMES/$loc-camera.ppm"; mv "$last" "$png"; rm -f "$FRAMES"/cam"$idx"-*.ppm; fi
            result INFO "$loc camera frame saved" "$png (check that it's upright; not added to the report)"
        else
            result WARN "$loc camera frame saved" "no frame written"
        fi
    done < "$dir/.list"
    rm -f "$dir/.list"
    write_summary
}

# ---------------------------------------------------------------------------
# suspend

# Seconds the system actually spent suspended, from the kernel's PM messages
# after a given epoch (falls back to the caller's wall-clock estimate).
suspended_seconds() {
    asroot journalctl -k --no-pager -o short-unix --no-hostname --since="@$1" 2>/dev/null \
        | awk '/PM: suspend entry/ { e = $1 } /PM: suspend exit/ { if (e) { printf "%d", $1 - e; exit } }'
}

wait_for_resume() {  # wait_for_resume SUCCESS_BEFORE FAIL_BEFORE TIMEOUT -> 0 resumed, 1 failed, 2 timed out
    local i=0 s f
    while [ "$i" -lt "$3" ]; do
        sleep 1; i=$((i + 1))
        s=$(readf /sys/power/suspend_stats/success); f=$(readf /sys/power/suspend_stats/fail)
        [ "${s:-0}" -gt "$1" ] && return 0
        [ "${f:-0}" -gt "$2" ] && return 1
    done
    return 2
}

cmd_suspend() {
    local nosusp=0 args=() a
    for a in "$@"; do [ "$a" = --no-suspend ] && nosusp=1 || args+=("$a"); done
    local cycles=${args[0]:-10} secs=${args[1]:-60}
    need_sudo
    local tsv="$OUT/suspend.tsv" i before after s0 f0 t0 t1 rc susp hw res woke wakeirq newwarn issues ok=0 resid_sum=0 resid_n=0 problems=""
    local hw0 hw1 slp0 slp1 slp hw_total=0
    section suspend "Suspend/resume: $cycles cycles of ${secs}s ($(date '+%F %H:%M'))"
    if [ "$nosusp" = 1 ]; then info "  (--no-suspend: running the checks without suspending)"; fi
    printf 'cycle\tresult\trtc_wake\tsuspended_s\thw_sleep_s\tslp_s0_s\tresidency_pct\twake_irq\tnew_warnings\tbefore\tafter\n' > "$tsv"
    : > "$OUT/suspend-warnings.txt"
    for i in $(seq 1 "$cycles"); do
        before=$(device_state)
        s0=$(readf /sys/power/suspend_stats/success); f0=$(readf /sys/power/suspend_stats/fail)
        hw0=$(readf /sys/power/suspend_stats/total_hw_sleep)
        slp0=$(asroot cat /sys/kernel/debug/pmc_core/slp_s0_residency_usec 2>/dev/null)
        t0=$(date +%s)
        info "  cycle $i/$cycles: suspending for ${secs}s..."
        if [ "$nosusp" = 1 ]; then
            sleep 2; rc=0
        else
            asroot rtcwake -m no -s "$secs" >/dev/null 2>&1
            if systemctl suspend; then
                wait_for_resume "${s0:-0}" "${f0:-0}" $((secs + 900)); rc=$?
            else
                rc=3
            fi
        fi
        t1=$(date +%s)
        # let devices, iptsd and the network come back
        for _ in $(seq 1 30); do
            sleep 1
            { [ "$(state_get "$before" iptsd)" = 0 ] || iptsd_active; } \
                && { [ "$(state_get "$before" wifi)" = 0 ] || wifi_up; } && break
        done
        sleep 3
        after=$(device_state)
        susp=$(suspended_seconds "$t0"); [ -z "$susp" ] && susp=$((t1 - t0))
        hw1=$(readf /sys/power/suspend_stats/total_hw_sleep)
        hw=$(awk -v a="${hw0:-0}" -v b="${hw1:-0}" 'BEGIN { printf "%d", (b - a) / 1000000 }')
        hw_total=$((hw_total + hw))
        slp1=$(asroot cat /sys/kernel/debug/pmc_core/slp_s0_residency_usec 2>/dev/null)
        slp=$(awk -v a="${slp0:-}" -v b="${slp1:-}" 'BEGIN { if (a != "" && b != "") printf "%d", (b - a) / 1000000; else print "?" }')
        res=$(awk -v h="${hw:-0}" -v s="$susp" 'BEGIN { if (s > 0) printf "%d", 100 * h / s; else print 0 }')
        woke=yes; [ "$nosusp" = 0 ] && [ "$((t1 - t0))" -gt $((secs + 45)) ] && woke=no
        wakeirq=$(readf /sys/power/pm_wakeup_irq)
        classify_warnings "$t0" > "$OUT/.cycle-warn"
        newwarn=$(grep -c '^\[NEW\]' "$OUT/.cycle-warn")
        { echo "== cycle $i"; cat "$OUT/.cycle-warn"; } >> "$OUT/suspend-warnings.txt"
        issues=""
        case $rc in
            1) issues+="suspend failed ($(readf /sys/power/suspend_stats/last_failed_dev)); " ;;
            2) issues+="no resume detected; " ;;
            3) issues+="systemctl suspend refused (inhibited?); " ;;
        esac
        for a in touch iptsd iptsd_inputs cover wifi bt cameras; do
            [ "$(state_get "$before" "$a")" != "$(state_get "$after" "$a")" ] && issues+="$a $(state_get "$before" "$a")->$(state_get "$after" "$a"); "
        done
        [ "$newwarn" -gt 0 ] && issues+="$newwarn new kernel warning(s); "
        if [ "$nosusp" = 0 ] && [ "$rc" = 0 ]; then
            resid_sum=$((resid_sum + res)); resid_n=$((resid_n + 1))
            [ "$res" -lt 50 ] && [ -n "${hw1:-}" ] && issues+="low S0ix residency ${res}%; "
        fi
        if [ -z "$issues" ]; then ok=$((ok + 1)); a=ok; else a="issues: ${issues%; }"; problems+="cycle $i: ${issues%; }. "; fi
        printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$i" "$a" "$woke" "$susp" "${hw:-?}" "$slp" "$res" "${wakeirq:-?}" "$newwarn" "$before" "$after" >> "$tsv"
        info "    $a (suspended ${susp}s, S0ix ${res}%, RTC wake $woke)"
    done
    rm -f "$OUT/.cycle-warn"
    if [ "$ok" = "$cycles" ]; then result PASS "All cycles resumed with devices intact" "$ok/$cycles"
    else result WARN "All cycles resumed with devices intact" "$ok/$cycles clean. $problems"; fi
    if [ "$resid_n" -gt 0 ] && [ "$hw_total" -eq 0 ]; then
        result WARN "Average S0ix residency" "hardware sleep counter never moved: no S0ix at all, or intel_pmc_core isn't reporting (see slp_s0_s in suspend.tsv)"
    elif [ "$resid_n" -gt 0 ]; then
        a=$((resid_sum / resid_n))
        if [ "$a" -ge 80 ]; then result PASS "Average S0ix residency" "${a}%"
        elif [ "$a" -ge 50 ]; then result WARN "Average S0ix residency" "${a}%"
        else result FAIL "Average S0ix residency" "${a}% (deep idle not reached; expect high battery drain)"; fi
    else
        result SKIP "Average S0ix residency" "no real suspend cycles"
    fi
    if grep -q $'\tno\t' "$tsv"; then result INFO "RTC wake from s2idle" "did not wake by itself in at least one cycle"
    elif [ "$nosusp" = 0 ]; then result PASS "RTC wake from s2idle"; fi
    write_summary
}

# ---------------------------------------------------------------------------
# drain

cmd_drain() {
    local nosusp=0
    [ "${1:-}" = --no-suspend ] && nosusp=1
    need_sudo
    local e0 e1 full c0 c1 t0 t1 s0 f0 hw0 hw1 hours drop rate res
    section drain "Overnight battery drain ($(date '+%F %H:%M'))"
    if ! e0=$(bat_energy) || ! full=$(bat_energy_full); then
        result SKIP "Battery drain while suspended" "no battery energy readings"; write_summary; return
    fi
    ac_online && info "WARNING: the charger is connected; unplug it for a meaningful result."
    c0=$(readf "$(bat_dir)/capacity"); t0=$(date +%s)
    s0=$(readf /sys/power/suspend_stats/success); f0=$(readf /sys/power/suspend_stats/fail)
    hw0=$(readf /sys/power/suspend_stats/total_hw_sleep)
    info "Battery at ${c0}%. Suspending now; leave it (e.g. overnight), then wake it with the power button."
    if [ "$nosusp" = 1 ]; then sleep 3
    elif ! systemctl suspend; then
        result FAIL "Battery drain while suspended" "systemctl suspend refused"; write_summary; return
    else
        wait_for_resume "${s0:-0}" "${f0:-0}" 172800
    fi
    sleep 5
    e1=$(bat_energy); c1=$(readf "$(bat_dir)/capacity"); t1=$(date +%s)
    hw1=$(readf /sys/power/suspend_stats/total_hw_sleep)
    hours=$(awk -v a="$t0" -v b="$t1" 'BEGIN { printf "%.2f", (b - a) / 3600 }')
    drop=$(awk -v a="$e0" -v b="$e1" -v f="$full" 'BEGIN { printf "%.2f", 100 * (a - b) / f }')
    rate=$(awk -v d="$drop" -v s="$((t1 - t0))" 'BEGIN { if (s > 0) printf "%.2f", d * 3600 / s; else print 0 }')
    res=$(awk -v a="${hw0:-0}" -v b="${hw1:-0}" -v s="$((t1 - t0))" 'BEGIN { if (s > 0) printf "%d", 100 * (b - a) / 1000000 / s; else print 0 }')
    {
        echo "start: $(date -d "@$t0" '+%F %H:%M') battery ${c0}% energy ${e0} uWh"
        echo "end:   $(date -d "@$t1" '+%F %H:%M') battery ${c1}% energy ${e1} uWh"
        echo "full:  ${full} uWh"
        echo "elapsed: ${hours} h, drop: ${drop}% of full, rate: ${rate} %/h ($(awk -v r="$rate" 'BEGIN { printf "%.1f", r * 24 }') %/day)"
        echo "S0ix residency over the period: ${res}%"
        echo "suspends during the period: $(( $(readf /sys/power/suspend_stats/success) - ${s0:-0} ))"
    } > "$OUT/drain.txt"
    result INFO "Elapsed" "${hours} h, battery ${c0}% -> ${c1}%"
    if awk -v r="$rate" 'BEGIN { exit !(r <= 0.6) }'; then result PASS "Drain rate while suspended" "${rate} %/h (7.1 estimate: under 0.4 %/h)"
    elif awk -v r="$rate" 'BEGIN { exit !(r <= 1.5) }'; then result WARN "Drain rate while suspended" "${rate} %/h (7.1 estimate: under 0.4 %/h)"
    else result FAIL "Drain rate while suspended" "${rate} %/h (7.1 estimate: under 0.4 %/h)"; fi
    result INFO "S0ix residency over the period" "${res}%"
    write_summary
}

# ---------------------------------------------------------------------------
# load

pkg_temp() {  # package temperature in °C
    local h l
    for h in /sys/class/hwmon/hwmon*; do
        [ "$(readf "$h/name")" = coretemp ] || continue
        for l in "$h"/temp*_label; do
            [ "$(readf "$l")" = "Package id 0" ] && { awk '{ printf "%d", $1 / 1000 }' "${l%_label}_input"; return; }
        done
    done
    for h in /sys/class/thermal/thermal_zone*; do
        [ "$(readf "$h/type")" = x86_pkg_temp ] && { awk '{ printf "%d", $1 / 1000 }' "$h/temp"; return; }
    done
    echo 0
}

fan_rpm() { cat /sys/class/hwmon/hwmon*/fan*_input 2>/dev/null | sort -n | tail -1 | grep . || echo 0; }

avg_mhz() { cat /sys/devices/system/cpu/cpu*/cpufreq/scaling_cur_freq 2>/dev/null | awk '{ s += $1; n++ } END { if (n) printf "%d", s / n / 1000; else print 0 }'; }

rapl_uj() { asroot cat /sys/class/powercap/intel-rapl:0/energy_uj 2>/dev/null || echo 0; }

cmd_load() {
    local secs=${1:-60} orig choices p e0 e1 t0 t1 tmax fmax msum n watts a end
    need_sudo
    section load "CPU load per platform profile, ${secs}s each ($(date '+%F %H:%M'))"
    if [ ! -w /sys/firmware/acpi/platform_profile ] && [ ! -r /sys/firmware/acpi/platform_profile ]; then
        result SKIP "Platform profiles" "/sys/firmware/acpi/platform_profile missing"; write_summary; return
    fi
    ac_online || info "WARNING: not on AC power; results will be limited by battery power limits."
    orig=$(readf /sys/firmware/acpi/platform_profile); RESTORE_PROFILE=$orig
    choices=$(readf /sys/firmware/acpi/platform_profile_choices)
    printf 'profile\tavg_pkg_watts\tmax_temp_c\tmax_fan_rpm\tavg_mhz\n' > "$OUT/load.tsv"
    for p in $choices; do
        printf '%s' "$p" | asroot tee /sys/firmware/acpi/platform_profile >/dev/null 2>&1 || { result WARN "Profile $p" "could not set"; continue; }
        info "  profile $p: idle 10 s, then ${secs}s of load..."
        sleep 10
        LOAD_PIDS=
        if have stress-ng; then stress-ng --cpu 0 --timeout "${secs}s" --quiet & LOAD_PIDS=$!
        else for _ in $(seq 1 "$(nproc)"); do ( while :; do :; done ) & LOAD_PIDS+="$! "; done; fi
        e0=$(rapl_uj); t0=$(date +%s.%N); tmax=0; fmax=0; msum=0; n=0
        end=$(( $(date +%s) + secs ))
        while [ "$(date +%s)" -lt "$end" ]; do
            sleep 2
            a=$(pkg_temp); [ "$a" -gt "$tmax" ] && tmax=$a
            a=$(fan_rpm); [ "$a" -gt "$fmax" ] && fmax=$a
            msum=$((msum + $(avg_mhz))); n=$((n + 1))
        done
        e1=$(rapl_uj); t1=$(date +%s.%N)
        # shellcheck disable=SC2086
        { kill $LOAD_PIDS; wait $LOAD_PIDS; } 2>/dev/null; LOAD_PIDS=
        watts=$(awk -v a="$e0" -v b="$e1" -v s="$t0" -v t="$t1" 'BEGIN { if (b > a && t > s) printf "%.1f", (b - a) / 1000000 / (t - s); else print "?" }')
        printf '%s\t%s\t%s\t%s\t%s\n' "$p" "$watts" "$tmax" "$fmax" "$((n ? msum / n : 0))" >> "$OUT/load.tsv"
        result INFO "Profile $p under load" "${watts} W package, max ${tmax} C, max fan ${fmax} rpm, avg $((n ? msum / n : 0)) MHz"
        info "  cooling down 20 s..."; sleep 20
    done
    printf '%s' "$orig" | asroot tee /sys/firmware/acpi/platform_profile >/dev/null 2>&1; RESTORE_PROFILE=
    local wmin wmax
    wmin=$(awk -F'\t' 'NR > 1 && $2 != "?" { print $2 }' "$OUT/load.tsv" | sort -n | head -1)
    wmax=$(awk -F'\t' 'NR > 1 && $2 != "?" { print $2 }' "$OUT/load.tsv" | sort -n | tail -1)
    if [ -n "$wmin" ] && awk -v a="$wmin" -v b="$wmax" 'BEGIN { exit !(b >= a * 1.1) }'; then
        result PASS "Platform profiles change power limits" "${wmin} W to ${wmax} W"
    elif [ -n "$wmin" ]; then
        result WARN "Platform profiles change power limits" "${wmin} W to ${wmax} W (no real difference)"
    else
        result SKIP "Platform profiles change power limits" "no package power readings"
    fi
    if awk -F'\t' 'NR > 1 && $4 > 0 { found = 1 } END { exit !found }' "$OUT/load.tsv"; then result PASS "Fan spins up under load"
    else result WARN "Fan spins up under load" "fan never reported above 0 rpm"; fi
    write_summary
}

# ---------------------------------------------------------------------------
# checklist

# id|section|check|how to test|helper
CHECKS=(
"t1|Touch & pen|Touchscreen tap and drag work across the whole screen, including the corners||touch"
"t2|Touch & pen|Two-finger scroll and pinch-zoom (e.g. in a browser)||"
"t3|Touch & pen|Pen draws with pressure|Use Xournal++, Krita or Inkscape and vary the pressure|"
"t4|Touch & pen|Pen hover, barrel button (right-click) and eraser end|Hover moves the cursor before contact|"
"t5|Touch & pen|Palm rejection: resting your hand while writing doesn't draw or click||"
"t6|Touch & pen|Touch and pen still work after suspend and resume||"
"k1|Type Cover|All keys, the Fn row (brightness, volume, media) and Fn lock||"
"k2|Type Cover|Keyboard backlight levels change with its key||"
"k3|Type Cover|Touchpad: tap, click, two-finger scroll, right-click, three/four-finger gestures||"
"k4|Type Cover|Detaching the cover switches to tablet mode|Desktop switches to tablet mode / on-screen keyboard|tablet"
"k5|Type Cover|Folding the cover behind the screen switches to tablet mode and disables keys||tablet"
"k6|Type Cover|Reattaching the cover: keyboard and touchpad work immediately||"
"k7|Type Cover|Closing the cover suspends (backlight off) and opening resumes||"
"d1|Display & sensors|Brightness slider and Fn brightness keys||"
"d2|Display & sensors|Auto-brightness reacts to light (cover the light sensor)||"
"d3|Display & sensors|Screen auto-rotates in tablet mode||"
"d4|Display & sensors|No flicker or artifacts|Your cmdline has i915.enable_psr=0|"
"d5|Display & sensors|120 Hz refresh rate available and selectable|Skip if you don't use it|"
"d6|Display & sensors|External display over USB-C / Thunderbolt|Skip if you have none|"
"c1|Cameras|Saved front camera frame is upright|Frames are in ~/sp9-test-frames/ (from the cameras step)|frames"
"c2|Cameras|Saved rear camera frame is upright (it was upside down on 7.1)||frames"
"c3|Cameras|Front camera works in an app|Browser webcam test via PipeWire, Snapshot, Kamoso or qcam|qcam"
"c4|Cameras|Rear camera works in an app||qcam"
"c5|Cameras|Cameras still work after suspend and resume||"
"a1|Audio|Speakers play on both left and right||speakers"
"a2|Audio|Hardware volume buttons change the volume||"
"a3|Audio|Internal microphone records (play back the recording)||mic"
"a4|Audio|Bluetooth audio|Skip if you have no Bluetooth headset|"
"n1|Network|Wi-Fi connects and stays stable||"
"n2|Network|Bluetooth device (e.g. your mouse) pairs and reconnects||"
"n3|Network|Wi-Fi and Bluetooth reconnect after resume||"
"p1|Power & ports|Charging over USB-C||"
"p2|Power & ports|Charging over Surface Connect||"
"p3|Power & ports|Battery percentage is plausible and updates||"
"p4|Power & ports|Power profile switching from the desktop (power saver / balanced / performance)||"
"p5|Power & ports|Fan spins up under load and quiets down afterwards||"
"p6|Power & ports|Power button suspends and wakes||"
"p7|Power & ports|USB-C data device (flash drive, hub, dock)|Skip if you have none|"
"s1|System|Boot reaches the desktop without errors or hangs||"
"s2|System|Reboot completes without hanging||"
"s3|System|Shutdown powers off fully (no hang, no immediate wake)||"
"s4|System|Hibernate and resume|Skip if you don't use hibernation|"
"s5|System|No freezes or crashes over a day or more of normal use||"
)

helper_run() {
    local node f
    case "$1" in
        touch)
            node=$(input_event_node "IPTSD Virtual Touchscreen")
            if have libinput && [ -n "$node" ]; then
                info "    Touch the screen for 10 s..."
                asroot timeout 10 libinput debug-events --device "$node" 2>/dev/null | grep -c TOUCH_DOWN | sed 's/^/    touch-down events: /'
            else info "    (needs libinput and the IPTSD touchscreen device)"; fi ;;
        tablet)
            node=$(input_event_node "Tablet Mode Switch")
            if have libinput && [ -n "$node" ]; then
                info "    Detach or fold the cover within 20 s, then put it back..."
                asroot timeout 20 libinput debug-events --device "$node" 2>/dev/null | grep -i switch | sed 's/^/    /'
            elif have evtest && [ -n "$node" ]; then
                info "    Detach or fold the cover, then press Enter"; read -r _
                asroot evtest --query "$node" EV_SW SW_TABLET_MODE
                if [ $? -eq 10 ]; then info "    tablet mode: ON"; else info "    tablet mode: OFF"; fi
            else info "    (needs libinput or evtest and the tablet mode switch device)"; fi ;;
        frames)
            find "$FRAMES" -maxdepth 1 -type f -printf '    %f\n' 2>/dev/null
            for f in "$FRAMES"/*.png "$FRAMES"/*.ppm; do [ -e "$f" ] && have xdg-open && xdg-open "$f" >/dev/null 2>&1 & done ;;
        qcam)
            if have qcam; then qcam >/dev/null 2>&1; else info "    qcam not installed; try a browser webcam test page or Snapshot/Kamoso."; fi ;;
        speakers)
            if have speaker-test; then speaker-test -c 2 -t wav -l 1 >/dev/null 2>&1
            elif have pw-play && [ -e /usr/share/sounds/alsa/Front_Left.wav ]; then pw-play /usr/share/sounds/alsa/Front_Left.wav; pw-play /usr/share/sounds/alsa/Front_Right.wav
            else info "    (needs speaker-test from alsa-utils)"; fi ;;
        mic)
            f=$(mktemp --suffix=.wav)
            info "    Recording 5 s, speak now..."
            if have pw-record; then timeout 5 pw-record --rate 48000 --channels 1 "$f" 2>/dev/null; pw-play "$f" 2>/dev/null
            elif have arecord; then arecord -q -d 5 -f S16_LE -r 48000 -c 1 "$f"; aplay -q "$f"
            else info "    (needs pw-record or arecord)"; fi
            rm -f "$f" ;;
    esac
}

cmd_checklist() {
    local redo=0 tsv="$OUT/checklist.tsv" entry id sec check how helper ans note status
    [ "${1:-}" = --redo ] && redo=1
    [ "$redo" = 1 ] && rm -f "$tsv"
    touch "$tsv"
    info "Manual checks. Answer y (works), n (broken), p (partly), s (skip / can't test),"
    info "h (run the helper, where offered) or q (quit and continue later)."
    for entry in "${CHECKS[@]}"; do
        IFS='|' read -r id sec check how helper <<< "$entry"
        grep -q "^$id"$'\t' "$tsv" && continue
        info ""
        info "[$sec] $check"
        [ -n "$how" ] && info "    $how"
        while :; do
            if [ -n "$helper" ]; then printf '  y/n/p/s/h/q? '; else printf '  y/n/p/s/q? '; fi
            read -r ans || ans=q
            case "$ans" in
                y|n|p|s) break ;;
                h) [ -n "$helper" ] && helper_run "$helper" ;;
                q) write_checklist; info "Saved; run 'checklist' again to continue."; return 0 ;;
            esac
        done
        note=
        if [ "$ans" != s ] && [ "$ans" != y ]; then printf '  note (what happened): '; read -r note || note=
        elif [ "$ans" = y ]; then printf '  note (optional, Enter to skip): '; read -r note || note=
        fi
        case "$ans" in y) status=works ;; n) status=broken ;; p) status=partial ;; s) status=skipped ;; esac
        printf '%s\t%s\t%s\n' "$id" "$status" "$(printf '%s' "$note" | tr '\t' ' ')" >> "$tsv"
    done
    write_checklist
    info "Checklist complete: $OUT/TESTED.md"
}

write_checklist() {
    local tsv="$OUT/checklist.tsv" entry id sec check how helper status note icon works=0 broken=0 partial=0 skipped=0
    {
        printf '# Manual checks: %s\n\n' "$KREL"
        printf '| Section | Check | Result | Notes |\n|---|---|---|---|\n'
        for entry in "${CHECKS[@]}"; do
            IFS='|' read -r id sec check how helper <<< "$entry"
            status=$(awk -F'\t' -v i="$id" '$1 == i { print $2 }' "$tsv" | tail -1)
            note=$(awk -F'\t' -v i="$id" '$1 == i { print $3 }' "$tsv" | tail -1 | sed 's/|/\\|/g')
            case "$status" in
                works) icon="✅ works"; works=$((works + 1)) ;;
                broken) icon="❌ broken"; broken=$((broken + 1)) ;;
                partial) icon="⚠️ partial"; partial=$((partial + 1)) ;;
                skipped) icon="⚪ skipped"; skipped=$((skipped + 1)) ;;
                *) icon="(not answered)" ;;
            esac
            printf '| %s | %s | %s | %s |\n' "$sec" "$check" "$icon" "$note"
        done
    } > "$OUT/TESTED.md"
    SEC_FILE="$OUT/.summary-checklist.md"
    {
        printf '## Manual checklist\n\n'
        printf '%s works, %s broken, %s partial, %s skipped. Details in TESTED.md.\n' "$works" "$broken" "$partial" "$skipped"
        if [ "$broken" -gt 0 ] || [ "$partial" -gt 0 ]; then
            printf '\n| Check | Result | Notes |\n|---|---|---|\n'
            grep -E '❌|⚠️' "$OUT/TESTED.md" | awk -F' \\| ' '{ print "| " $2 " | " $3 " | " $4 }'
        fi
    } > "$SEC_FILE"
    write_summary
}

# ---------------------------------------------------------------------------

usage() { sed -n '2,/^$/{s/^# \{0,1\}//;p}' "${BASH_SOURCE[0]}"; }

main() {
    local cmd=${1:-}
    [ $# -gt 0 ] && shift
    case "$cmd" in
        collect|cameras|suspend|drain|load|checklist|all) ;;
        -h|--help|help|"") usage; exit 0 ;;
        *) echo "Unknown command: $cmd" >&2; usage >&2; exit 2 ;;
    esac
    mkdir -p "$OUT"
    info "Report directory: $OUT"
    case "$cmd" in
        collect) cmd_collect ;;
        cameras) cmd_cameras ;;
        suspend) cmd_suspend "$@" ;;
        drain) cmd_drain "$@" ;;
        load) cmd_load "$@" ;;
        checklist) cmd_checklist "$@" ;;
        all) cmd_collect; cmd_cameras; cmd_checklist; cmd_suspend 10 60 ;;
    esac
    report_hint
}

main "$@"
